[package]
name = "glow_js"
version = "0.1.0"
authors = ["JasonWang <1103870790@qq.com>"]
edition = "2018"
default-run = "glow_example"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "glow_core"
path = "src/core/lib.rs"

[[bin]]
name = "glow_example"
path = "src/main.rs"

[dependencies]
