[package]
name = "js-vm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
description = "Stack-based bytecode interpreter for JustScript"

[dependencies]
js-syntax.workspace = true
js-runtime.workspace = true
js-bytecode.workspace = true
js-diagnostics.workspace = true
js-parser.workspace = true
