#!/usr/bin/env bash
set -euo pipefail

unicode_version=17.0.0
source_url="https://www.unicode.org/Public/${unicode_version}/ucd/DerivedCoreProperties.txt"
source_sha256=24c7fed1195c482faaefd5c1e7eb821c5ee1fb6de07ecdbaa64b56a99da22c08

script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
repo_root=$(cd -- "$script_dir/.." && pwd)
output="$repo_root/crates/js-lexer/src/unicode_id_tables.rs"
temp_dir=$(mktemp -d)
trap 'rm -r -- "$temp_dir"' EXIT
source_file="$temp_dir/DerivedCoreProperties.txt"
generated_file="$temp_dir/unicode_id_tables.rs"

if command -v wget >/dev/null 2>&1; then
  wget -q "$source_url" -O "$source_file"
else
  curl -fsSL "$source_url" -o "$source_file"
fi

actual_sha256=$(sha256sum "$source_file" | awk '{print $1}')
if [[ "$actual_sha256" != "$source_sha256" ]]; then
  echo "error: Unicode data checksum mismatch: $actual_sha256" >&2
  exit 1
fi

emit_property() {
  local property=$1
  local rust_name=$2
  printf 'pub(super) const %s: &[(u32, u32)] = &[\n' "$rust_name"
  awk -v wanted="$property" '
    /^[0-9A-F]/ {
      data = $0
      sub(/#.*/, "", data)
      split(data, fields, ";")
      range = fields[1]
      property = fields[2]
      gsub(/[[:space:]]/, "", range)
      gsub(/^[[:space:]]+|[[:space:]]+$/, "", property)
      if (property != wanted) next
      count = split(range, endpoints, /\.\./)
      start = endpoints[1]
      end = count == 2 ? endpoints[2] : endpoints[1]
      printf "    (0x%s, 0x%s),\n", start, end
    }
  ' "$source_file"
  printf '];\n\n'
}

{
  printf '// @generated by scripts/generate-unicode-ident-tables.sh; do not edit.\n'
  printf '// Source: %s\n' "$source_url"
  printf '// SHA-256: %s\n\n' "$source_sha256"
  printf 'pub(super) const UNICODE_VERSION: (u8, u8, u8) = (17, 0, 0);\n\n'
  emit_property ID_Start ID_START_RANGES
  emit_property ID_Continue ID_CONTINUE_RANGES
} > "$generated_file"

mv -- "$generated_file" "$output"
